### ISSUE TITLE
Dataset link has expired

### ISSUE THREAD

**Issue by CandiceHan123** [yue-zhongqi/gcm-cf#10]
Hello, in the data set division link you gave（https://www.mpi-inf.mpg.de/departments/computer-vision-and-machine-learning/research/zero-shot-learning/zero-shot-learning-the-good-the-bad-and-the-ugly/  ）, I click the link in the page but can't download it.

**Comment by yue-zhongqi** [comment]
Try
https://www.mpi-inf.mpg.de/departments/computer-vision-and-machine-learning/research/zero-shot-learning/zero-shot-learning-the-good-the-bad-and-the-ugly
